apiVersion: apps/v1
kind: Deployment
metadata:
  name: lounge
  labels:
    app: lounge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lounge
  strategy:
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lounge
    spec:
      initContainers:
        - name: migrate
          image: alexb04/opensuse-lounge:1.0
          imagePullPolicy: IfNotPresent
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: env-cfm
            - secretRef:
                name: app-key
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_PASSWORD
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_DATABASE
      containers:
        - image: alexb04/opensuse-lounge:1.0
          name: lounge
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-cfm
            - secretRef:
                name: mail-secret
            - secretRef:
                name: app-key

          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_PASSWORD

            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: MYSQL_DATABASE

      imagePullSecrets:
        - name: regcred
