apiVersion: v1
data:
  APP_DEBUG: "false"
  APP_ENV: production
  APP_FAKER_LOCALE: en_US
  APP_FALLBACK_LOCALE: en
  APP_LOCALE: en
  APP_MAINTENANCE_DRIVER: file
  APP_TIMEZONE: UTC
  APP_URL: https://lounge-dev.cloudnativemauritius.com
  ASSET_URL: https://lounge-dev.cloudnativemauritius.com
  BCRYPT_ROUNDS: "12"
  BROADCAST_CONNECTION: log

  AWS_ACCESS_KEY_ID: ""
  AWS_BUCKET: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ""
  AWS_USE_PATH_STYLE_ENDPOINT: "false"

  CACHE_PREFIX: ""
  CACHE_STORE: redis

  DB_CONNECTION: mysql
  DB_HOST: lounge-mysql
  DB_PORT: "3306"

  FILESYSTEM_DISK: local

  LOG_CHANNEL: stack
  LOG_DEPRECATIONS_CHANNEL: "null"
  LOG_LEVEL: debug
  LOG_STACK: single

  MEMCACHED_HOST: 127.0.0.1
  PHP_CLI_SERVER_WORKERS: "4"
  QUEUE_CONNECTION: sync

  REDIS_CLIENT: predis
  REDIS_HOST: redis-svc
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"

  SESSION_DOMAIN: "null"
  SESSION_DRIVER: database
  SESSION_ENCRYPT: "false"
  SESSION_LIFETIME: "120"
  SESSION_PATH: /

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: env-cfm
